name: Release Binary on Release Creation

on:
  release:
    types: [created]
jobs:
  build-and-upload:
    name: Build and Upload Binary
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Run Make build
        run: make build

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/osmosis-publisher
          asset_name: osmosis-publisher-${{ github.event.release.tag_name }}-amd64
          asset_content_type: application/octet-stream